### ISSUE TITLE
Return root selector

### ISSUE THREAD

**Issue by LeusMaximus** [jonathantneal/precss#10]
For example, we have this situation:

``` sass
.block {
    &__element {
        display: none;
    }
}
```

It compiles to

``` css
.block__element {
    display: none;
}
```

Then we want add state to `.block`. For example add active state and change styles on element.

``` sass
.block {
  $root: .block;

  &__element {
    display: none;

    $(root)_active & {
      display: block;
    }
  }
}
```

It compiles to 

``` css
.block__element {
  display: none;
}
.block_active .block__element {
  display: block;
}
```

But I saw an interesting solution for stylus in [this article](http://blog.legomushroom.com/2014/06/nesting-tree-traversal-in-stylus/).

Is it possible do something in precss? Or is there some other solution?

**Comment by LeusMaximus** [comment]
There is another point
In Sass if we write `$root: &` we get `.block_active .block__element` :
```sass
.block {
  $root: &;

  &__element {
    display: none;
    
    #{$root}_active & {
      display: block;
    }
  }
}
```
```css
.block__element {
  display: none;
}
.block_active .block__element {
  display: block;
}
```
But in precss we get `.block__element_active` instead `.block_active`. So `$root: &` change dynamically. Is it possible change this behavior?
```sass
.block {
  $root: &;

  &__element {
    display: none;
    
    $(root)_active & {
      display: block;
    }
  }
}
```
```css
.block__element {
  display: none;
}
.block__element_active .block__element {
  display: block;
}
```

**Comment by jonathantneal** [comment]
This is because the variables are compiled before the nesting is flattened. By the time it reads `$(root)_active &` it has become `&_active &`. Until precss can allow more interoperability between the plugins, this is a bug I can’t yet fix.

```scss
.block {
	$root: .block;

	&__element {
		display: none;

		$(root)_active & {
			display: block;
		}
	}
}
```

This is how you could work around it, but it’s not what either of us really want. :)
