### ISSUE TITLE
issue in variable conversion

### ISSUE THREAD

**Issue by iiison** [jonathantneal/precss#103]
I am using variable to add some CSS rules and some rules are not picking their values, the remains same. This is my code: 
```css
  $gridName:   grid !default;
  $colName:   col !default;
  $attributeName: class !default;

  [ $attributeName ~= "$gridName" ],
  [ $attributeName *= "$gridName-" ],
  [ $attributeName *= "$gridName_" ]{
    box-sizing: border-box;
    display: flex;
    flex-flow: row wrap;
    margin: 0 (-$gutter/2);
  }
```
after conversion it becomes:

```css
[class*="$gridName-"],
[class*="$gridName_"],
[class~=grid] {  /* observe that only this variable was converted, above 2 remained same */
    box-sizing: border-box;
    display: flex;
    flex-flow: row wrap;
    margin: 0 (-1rem/2)
}
```

Here is the [link to my webpack configurations](https://gist.github.com/iiison/ad75f149827666788558df01a91ff02a)
