### ISSUE TITLE
Cannot resolve #{$var} correctly

### ISSUE THREAD

**Issue by whidy** [jonathantneal/precss#114]
I have tried many times to resolve code like this below correctly,

```scss
.component {
  $c: &;
  padding: 2vw;
  &__card {
    background-color: #fff;
    &:hover #{$c}__name {
      color: #bada55;
    }
  }
  &__name {
    color: #000;
  }
  &__button {
    background-color: blue;
    color: #fff;
  }
}
```

But, it never works well, **precss 2.0.0** would throw an error:

```bash
    ERROR in ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./src/style.css
    Module build failed: Unknown word (7:28)

       5 |     background-color: #FFF;
       6 |   }
    >  7 |   .component__card:hover #{.component__card}__name
         |                            ^
       8 |       color: #BADA55;
       9 |     }
      10 |   .component__name {
```

Then I tried upgrade **precss 3.1.0**, it works, but not well.

Which I expect result should be like this:

```css
.component {
  padding: 2vw;
}

.component__card {
  background-color: #fff;
}

.component__card:hover .component__name {
  color: #bada55;
}

.component__name {
  color: #000;
}

.component__button {
  background-color: blue;
  color: #fff;
}
```

You can also try that sass code compile online <http://sass.js.org/>.

But truely result is below:

```css
.component {
  padding: 2vw;
}
  .component__card {
    background-color: #fff;
  }
  .component__card:hover .component__card__name {
      color: #bada55;
    }
  .component__name {
    color: #000;
  }
  .component__button {
    background-color: blue;
    color: #fff;
  }
```

Is it a bug? And how to solute the problem?
