### ISSUE TITLE
Can not resolve @extend with @import

### ISSUE THREAD

**Issue by zongwei007** [jonathantneal/precss#118]
I use precss 3.1.2 and found something strange like this:

```scss
//foo.scss
%foo {
  font-size: 12px;
}

//bar.scss
@import './foo';

.title {
  @extend %foo;
  float: left;
}
```

I expect result is:

```css
.title {
  font-size: 12px;
  float: left;
}
```

But finally it is:

```css
%foo {
  font-size: 12px;
}

.title {
  float: left;
}
```

I try to modified the `index.bundle.js` of precss, change variable `plugins`  from

```javascript
const plugins = [
	postcssExtendRule,
	postcssAdvancedVariables,
        ...
];
```

to

```javascript
const plugins = [
	postcssAdvancedVariables,
	postcssExtendRule,
        ...
];
```

It seem to work well now.
