### ISSUE TITLE
@define-mixin using if conditions

### ISSUE THREAD

**Issue by asifshirazi** [jonathantneal/precss#12]
I'm trying to define a mixin using IF conditions, here is my css:
```css
    @define-mixin font-smoothing $value: on {
        @if $value == on {
            -webkit-font-smoothing: antialiased;
        }
        @else {
            -webkit-font-smoothing: subpixel-antialiased;
        }
        -moz-osx-font-smoothing: auto;
    }
```
But it seems that it is not worked as I expected
