### ISSUE TITLE
@mixin arguments causing parse error

### ISSUE THREAD

**Issue by stevenvachon** [jonathantneal/precss#135]
```scss
@mixin border-shadow($inset: inset) {
  border: 1px solid silver;
  @if $inset == inset {
    box-shadow: inset 1px 1px 1px 0px, black;
  }
  @else if $inset == outset {
    box-shadow: 1px 1px 1px 0px black;
  }
}

a {
  @include border-shadow(inset);
  color: rebeccapurple;
}
```
```
"precss: /cp-pen-styles:6:13: Could not resolve the variable \"$inset\" within \"if $inset == outset\""
```
