### ISSUE TITLE
how to do tailwindcss-like @apply to extend rules

### ISSUE THREAD

**Issue by muayyad-alsadi** [jonathantneal/precss#137]
hi

is there a way to do something like this

```css

.px_s {padding-left: 8px; padding-right: 8px;}
.py_xs {padding-left: 4px; padding-right: 4px;}
.bg_primary {background-color: #acf;}

.btn {
@apply .px_s .py_xs .bg_primary
}
```

because with `@mixin` from `postcss-advanced-variables` 
I have to define small padding on x twice, once as a class rule '.px_s' and once as a mixing
