### ISSUE TITLE
Add postcss-property-lookup plugin

### ISSUE THREAD

**Issue by ai** [jonathantneal/precss#29]
https://github.com/simonsmith/postcss-property-lookup

```css
.icon {
    width: 20px;
    height: @width;
}
```
