### ISSUE TITLE
Function for darken/lighten

### ISSUE THREAD

**Issue by marcustisater** [jonathantneal/precss#38]
Hello Jonathan, 

I know there is a darken/lighten functionality for Sass colors. I think it's a inbuilt function in Sass, are there any possible for implementing it for precss in postcss? 

http://sass-lang.com/documentation/Sass/Script/Functions.html#darken-instance_method

Thank you

**Comment by fingermaster** [comment]
Hello, 

I used  "postcss-color-function"
https://github.com/postcss/postcss-color-function

Peter

**Comment by marcustisater** [comment]
Thank you. Any possible of this feature for this plugin tho?

**Comment by fingermaster** [comment]
It looks like he uses the plugin in this bundle already. Have you tried using it on a test selector? I've been using it as a standalone plugin - but this syntax works for me.

```css
.lighten {
  background-color: color(red a(70%));
   &:hover {
    background-color: color(red lightness(80%));
  }
}
```
