### ISSUE TITLE
a problem @at-root

### ISSUE THREAD

**Issue by ghost** [jonathantneal/precss#40]
there has a problem with precss,when i use '@at-root' like you has said it doesn't work
this is the postcss file:

``` postcss
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
```

and then the output file:

``` css
.test{
  color:red;
  @at-root{
    .test2{
      color:blue;
    }
  }
}
```

i tried  to ask the author of '@at-root' and he said that this is wrong in precss and it run normal in postcss

**Comment by sashamjolnir** [comment]
+1
What progress has the task?

**Comment by mushiuta** [comment]
i‘m sorry to say that it no reply at all and finally i change it to sass

**Comment by ai** [comment]
@jonathantneal Any updates?

**Comment by jonathantneal** [comment]
I went to https://jonathantneal.github.io/precss/ and tested the following SCSS:

```scss
.test{
  color:red;

  @at-root{
    .test2{
      color:blue;
    }
  }
}
```

And I got this result:

```css
.test2 {
  color:blue;
}

.test{
  color:red
}
```
