### ISSUE TITLE
a problem with @define-extend

### ISSUE THREAD

**Issue by ghost** [jonathantneal/precss#41]
there has a problem with '@define-extend' when i use '@extend' in a media query,it wrong and tell me the defined extend is not defined
this is the input:

``` scss
@define-extend base{
    color:red;
}

@define-mixin mt $name{
    @for $i from 1 to 10 by 1{
        .$(name)-$i{
            @extend base;
            font-size:$(i)px;
        }
    }
}

@custom-media --m (width>1000px);

@define-mixin mt2{
    @mixin mt n1;
    @media(--m){
        @mixin mt n2;
    }
}

@mixin mt2;
```

and i test in your site it‘s output:

``` css
.n1-1, .n1-2, .n1-3, .n1-4, .n1-5, .n1-6, .n1-7, .n1-8, .n1-9, .n1-10 {
    color:red;
}

.n1-1 {
    font-size:1px;
}

.n1-2 {
    font-size:2px;
}

.n1-3 {
    font-size:3px;
}

.n1-4 {
    font-size:4px;
}

.n1-5 {
    font-size:5px;
}

.n1-6 {
    font-size:6px;
}

.n1-7 {
    font-size:7px;
}

.n1-8 {
    font-size:8px;
}

.n1-9 {
    font-size:9px;
}

.n1-10 {
    font-size:10px;
}

@media(min-width: 1000.001px) {

    .n2-1 {
        font-size:1px;
    }

    .n2-2 {
        font-size:2px;
    }

    .n2-3 {
        font-size:3px;
    }

    .n2-4 {
        font-size:4px;
    }

    .n2-5 {
        font-size:5px;
    }

    .n2-6 {
        font-size:6px;
    }

    .n2-7 {
        font-size:7px;
    }

    .n2-8 {
        font-size:8px;
    }

    .n2-9 {
        font-size:9px;
    }

    .n2-10 {
        font-size:10px;
    }
}
```
