### ISSUE TITLE
can't corvet keyframes in loops

### ISSUE THREAD

**Issue by zhouwenbin** [jonathantneal/precss#44]
``` css
@for $i from 1 to 7{
  @keyframes ani$i {
    0% {
      background-position: 0 calc(-73px * ($i - 1));
    }

    100% {
      background-position: -2117px calc(-73px * ($i - 1));
    }
  }
  .ani$i{
    background-position: 0 calc(-73px * ($i - 1));
  }
  .ani$i:hover {
      animation: ani$i 1s steps(29);
    }
}
```
