### ISSUE TITLE
@extend & support

### ISSUE THREAD

**Issue by knynkwl** [jonathantneal/precss#54]
```
%extend {
  .parent &{
    display: none;
  }
}
```

compiles to:

```
.parent %extend{
  display: none;
}
```

**Comment by jonathantneal** [comment]
I just went to https://jonathantneal.github.io/precss/ and tested the following CSS:

```scss
%extend {
  .parent & {
    display: none;
  }
}

.test {
  @extend %extend;
}
```

And the result was:

```scss
.parent .test {
  display: none;
}
```
