### ISSUE TITLE
Errors when I have `@` in my CSS

### ISSUE THREAD

**Issue by furzeface** [jonathantneal/precss#82]
Error:
```sh
postcss-property-lookup: /Users/.../styles/main.css:742:1: Unable to find property @todo in .todo::before
```
or
```sh

```

Is there a way round having `@` symbols in my CSS?

I use them as follows in my CSS:
```css
.todo::before {
  content: '@todo: ';
}
```
and 
```css
@supports (display: grid) {
  .grid-layout--a {
    display: -ms-grid;
    display: grid;
   }
}
```

For example. 

Thanks.
