### ISSUE TITLE
Some more W3C syntax superpowers

### ISSUE THREAD

**Issue by doasync** [jonathantneal/precss#99]
**Add** these W3C syntax superpowers (from [cssnext](http://cssnext.io/)):
_______
https://github.com/SuperOl3g/postcss-image-set-polyfill
([W3C](https://drafts.csswg.org/css-images-4/#image-set-notation))
```css
.foo {
    background-image: image-set(url(img/test.png) 1x,
                                url(img/test-2x.png) 2x,
                                url(my-img-print.png) 600dpi);
}
```
_______
https://github.com/postcss/postcss-color-gray
([W3C](https://drafts.csswg.org/css-color/#grays))
```
.foo {
  color: gray(80, 30%);
}
```
_______
https://github.com/postcss/postcss-color-hex-alpha
([W3C](https://drafts.csswg.org/css-color/#hex-notation))
```
.foo {
  color: #0000ffcc;
}
```
_______
